/* midifile.h */
typedef struct {
	...
	DWORD           dt;
	DWORD           dwAbsPos;
	DWORD           iMsgSize;
	BYTE *data;
	DWORD data_sz;
	...
} MIDI_MSG;

/* midifile.c */
MIDI_MSG msg;
... 
bool midiReadGetNextMessage(const MIDI_FILE *_pMF, int iTrack, MIDI_MSG *pMsg) {
	...
	pMsg->iType = (tMIDI_MSG)((*pTrack->ptr) & 0xf0);
	...
}

/* m2rtttl.c */
while(midiReadGetNextMessage(mf, i, &msg)) {
	...
	if (iCurrPlayingNote==msg.MsgData.NoteOff.iNote) {
		...
		iCurrPlayingNote = -1;
		...
	}
	...
	if (iCurrPlayingNote==-1) {
		...
		iCurrPlayingNote = msg.MsgData.NoteOn.iNote;
		...
	}
	...
}
